/* ─── mock news data (shared between list + detail pages) ─── */

export const newsMock = [
  {
    id: 'news-001',
    title: 'Tinnten B2B Pazarı 2025 Yılında %40 Büyüme Kaydetti',
    subtitle: 'Platform verileri, satıcı sayısının 12 bin\'e ulaştığını ve işlem hacminin rekor kırdığını gösteriyor.',
    slug: 'tinnten-b2b-pazari-2025-buyume',
    category: { id: 'cat-3-1', name: 'Platform Haberleri' },
    tags: ['büyüme', 'platform', 'b2b', '2025'],
    contentType: 'richSections',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop',
    author: { name: 'Editör Ekibi', avatar: 'EE' },
    publishedAt: '24.05.2025',
    updatedAt: '24.05.2025',
    viewCount: 4821,
    richSections: [
      { heading: 'Genel Değerlendirme', body: '<p>2025 yılının ilk çeyreğinde Tinnten platformu, geçen yılın aynı dönemine göre %40\'lık büyüme kaydetti.</p>', order: 1 },
      { heading: 'Satıcı Ekosistemi', body: '<p>Aktif satıcı sayısı 12.000\'i aşarken yeni satıcı başvuruları da %65 artış gösterdi.</p>', order: 2 },
    ],
  },
  {
    id: 'news-002',
    title: 'Yapay Zeka Destekli Tedarikçi Eşleştirme Özelliği Yayında',
    subtitle: 'Yeni AI motoru, alıcı profiline göre en uygun tedarikçileri 3 saniyede sıralıyor.',
    slug: 'yapay-zeka-tedarikci-eslestirme',
    category: { id: 'cat-1-1', name: 'Yapay Zeka' },
    tags: ['yapay zeka', 'ai', 'tedarikçi', 'özellik'],
    contentType: 'richSections',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=240&fit=crop',
    author: { name: 'Teknoloji Editörü', avatar: 'TE' },
    publishedAt: '22.05.2025',
    updatedAt: '23.05.2025',
    viewCount: 3102,
    richSections: [
      { heading: 'Nasıl Çalışıyor?', body: '<p>Model, 200\'den fazla parametreyi analiz ederek en uygun tedarikçileri sıralar.</p>', order: 1 },
    ],
  },
  {
    id: 'news-003',
    title: 'Lojistik Sektöründe Dijitalleşme Hızlanıyor',
    subtitle: 'ERP entegrasyon talepleri 6 ayda 3 kat arttı; şirketler verimlilik arayışında.',
    slug: 'lojistik-sektoru-dijitalleme',
    category: { id: 'cat-4-1', name: 'Lojistik' },
    tags: ['lojistik', 'erp', 'dijitalleşme', 'entegrasyon'],
    contentType: 'html',
    status: 'draft',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=240&fit=crop',
    author: { name: 'Sektör Analisti', avatar: 'SA' },
    publishedAt: null,
    updatedAt: '21.05.2025',
    viewCount: 0,
    htmlContent: '<h2>Sektörde Dönüşüm</h2><p>Son altı ayda ERP entegrasyon taleplerinde ciddi bir artış gözlemlendi...</p>',
  },
  {
    id: 'news-004',
    title: 'Borsa İstanbul\'da Teknoloji Şirketleri Rekor Kırdı',
    subtitle: 'BIST Teknoloji Endeksi yılbaşından bu yana %28 değer kazandı.',
    slug: 'bist-teknoloji-rekor',
    category: { id: 'cat-2-1', name: 'Borsa' },
    tags: ['borsa', 'bist', 'teknoloji', 'yatırım'],
    contentType: 'sections',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=240&fit=crop',
    author: { name: 'Finans Editörü', avatar: 'FE' },
    publishedAt: '20.05.2025',
    updatedAt: '20.05.2025',
    viewCount: 6743,
    content: [
      { heading: 'Endeks Performansı', text: 'BIST Teknoloji Endeksi bu yıl %28 artış kaydetti.', order: 1 },
      { heading: 'Öne Çıkan Şirketler', text: 'Logo Yazılım ve Aselsan en çok değer kazanan hisseler arasında yer aldı.', order: 2 },
    ],
  },
  {
    id: 'news-005',
    title: 'Tinnten Pro Üyelik Avantajları Genişledi',
    subtitle: 'Pro üyeler artık öncelikli destek, gelişmiş analitik ve özel AI kredileri kazanıyor.',
    slug: 'tinnten-pro-avantajlar',
    category: { id: 'cat-3-1', name: 'Platform Haberleri' },
    tags: ['pro', 'üyelik', 'avantaj', 'ai'],
    contentType: 'richSections',
    status: 'draft',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=240&fit=crop',
    author: { name: 'Ürün Ekibi', avatar: 'UE' },
    publishedAt: null,
    updatedAt: '19.05.2025',
    viewCount: 0,
    richSections: [
      { heading: 'Yeni Avantajlar', body: '<p>Pro üyelik paketine üç yeni özellik eklendi: öncelikli destek hattı, gelişmiş analitik paneli ve aylık 500 AI kredisi.</p>', order: 1 },
    ],
  },
];

export const statusMeta = {
  published: { label: 'Yayında', variant: 'success' },
  draft: { label: 'Taslak', variant: 'warning' },
  archived: { label: 'Arşivlendi', variant: 'muted' },
};

export const contentTypeMeta = {
  richSections: { label: 'Zengin Bölümler' },
  sections: { label: 'Bölümler' },
  html: { label: 'HTML' },
  markdown: { label: 'Markdown' },
};
